
import React, { useState } from 'react';
import SyllabusInput from './SyllabusInput';
import AnalyticsView from './AnalyticsView';

type Tab = 'syllabus' | 'analytics' | 'qbank';

const InstructorDashboard: React.FC = () => {
  const [activeTab, setActiveTab] = useState<Tab>('syllabus');

  const renderContent = () => {
    switch (activeTab) {
      case 'syllabus':
        return <SyllabusInput />;
      case 'analytics':
        return <AnalyticsView />;
      case 'qbank':
        return <div className="p-6 bg-gray-800 rounded-lg"><h2 className="text-2xl font-bold">Question Bank Management</h2><p className="mt-4 text-gray-400">Feature coming soon. Here you will be able to manually create, edit, and manage all questions in the database, including those generated by the AI.</p></div>;
      default:
        return null;
    }
  };
  
  const TabButton: React.FC<{tabName: Tab; label: string}> = ({ tabName, label }) => (
    <button
        onClick={() => setActiveTab(tabName)}
        className={`px-4 py-2 font-medium text-sm rounded-md transition-colors duration-200 ${
            activeTab === tabName
            ? 'bg-blue-600 text-white'
            : 'text-gray-300 hover:bg-gray-700'
        }`}
    >
        {label}
    </button>
  );

  return (
    <main className="container mx-auto p-4 sm:p-6 lg:p-8">
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-white">Instructor Console</h1>
        <p className="mt-1 text-gray-400">Manage course content, generate questions, and analyze student performance.</p>
      </div>

      <div className="mb-6 border-b border-gray-700">
        <nav className="flex space-x-2" aria-label="Tabs">
            <TabButton tabName="syllabus" label="Syllabus & AI Generation" />
            <TabButton tabName="analytics" label="Analytics" />
            <TabButton tabName="qbank" label="Question Bank" />
        </nav>
      </div>
      
      <div>{renderContent()}</div>
    </main>
  );
};

export default InstructorDashboard;
